baseURL = "https://chenningg.com/"
enableRobotsTXT = true
googleAnalytics = "UA-176432250-1"
languageCode = "en-us"
pygmentsStyle = "dracula"
sectionPagesMenu = "main"
theme = "haru"
title = "Chen Ning"

[params]
author = "Chen Ning"
description = "My personal portfolio site, where I blog about code and other musings."

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = -90

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = -80

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = -70

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = -70
