baseURL = "https://chenningg.com/"
description = "Welcome to my personal portfolio site, where I blog about code and other musings!"
enableRobotsTXT = true
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "haru"
title = "Chen Ning"

[permalinks]
posts = "/blog/:year/:title/"
