description = "A minimal blogging and portfolio theme for Hugo."
features = []
homepage = "http://chenningg.com/"
license = "MIT"
licenselink = "https://github.com/chenningg/haru/blob/master/LICENSE"
min_version = "0.74.0"
name = "Haru"
tags = []

[author]
homepage = "https://chenningg.com"
name = "Chen Ning"

[permalinks]
posts = "/blog/:year/:title/"
